services:
  api:
    build:
      context: api
      target: final
    env_file:
      - .env
      - api/.env
    ports:
      - 3000:3000
    networks:
      - db_network

  tg-bot:
    build:
      context: tg-bot
      target: final
    env_file:
      - .env
      - tg-bot/.env
    ports:
      - 3001:3001
    networks:
      - db_network

  postgres:
    image: postgres
    restart: always
    command: postgres -c 'max_connections=2000'
    volumes:
      - ./data/pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=portfolio
      - POSTGRES_DB=portfolio
    ports:
      - "5436:5432"
    networks:
      - db_network


networks:
  db_network:
    driver: bridge

